//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeMaster.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        public int instrument_token { get; set; }
        public int exchange_token { get; set; }
        public string tradingsymbol { get; set; }
        public string name { get; set; }
        public decimal last_price { get; set; }
        public string expiry { get; set; }
        public decimal strike { get; set; }
        public decimal tick_size { get; set; }
        public int lot_size { get; set; }
        public string instrument_type { get; set; }
        public string segment { get; set; }
        public string exchange { get; set; }
        public int Id { get; set; }
    }
}
